### ISSUE TITLE
How do I reference variables exported from a Scss file?

### ISSUE THREAD

**Issue by ashikahmed3230** [ANONYMOUS-U7P4L/MY-OPEN-FILES#8]
How do I reference variables exported from a Scss file?

```scss

//index.scss

$--color-primary: #75126d;

:export {
  theme: $--color-primary;
}

```

```scss

import color from './index.scss'

console.log(color); 

/**log

@charset "UTF-8";

:export {
  theme: #75126d;
}
**/
``````scss

There's no such convention in vite.
